global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'postgres'
    metrics_path: /metrics
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'kafka'
    metrics_path: /metrics
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: 'elasticsearch'
    metrics_path: /metrics
    static_configs:
      - targets: ['elasticsearch-exporter:9114']

  - job_name: 'auth-svc'
    metrics_path: /metrics
    static_configs:
      - targets: ['auth-svc:8006']

  - job_name: 'profiles-svc'
    metrics_path: /metrics
    static_configs:
      - targets: ['profiles-svc:8080']
